---
- hosts: all
  become: yes
  tasks:
  - name: install apache2 on server
    apt:
       name: apache2   
       state: present
  - name: install git on server
    apt:
        name: git
        state: present 
     
                
