---
- hosts: 172.31.33.68
  become: yes
  tasks:
  - name : execute linux command
    command: hostname -f
    register: myresult
  - name: i want to see task result
    debug:
       msg: "{{myresult}}"
  - name: install pip
    apt:
       name: python3-pip
       state: present
    when:  myresult.stderr == ""     